"""empty message

Revision ID: 25e28b50876a
Revises: 95ff8521163d
Create Date: 2023-12-31 18:20:44.373012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e28b50876a'
down_revision = '95ff8521163d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)

    # ### end Alembic commands ###
