"""AuthUser added about_me and last_seen columns

Revision ID: 271dd75f56e2
Revises: 7e547b2e2a11
Create Date: 2023-11-11 18:37:36.195604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271dd75f56e2'
down_revision = '7e547b2e2a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
