"""Added posts table

Revision ID: 5c3fe900651f
Revises: 271dd75f56e2
Create Date: 2023-11-20 19:47:33.809791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3fe900651f'
down_revision = '271dd75f56e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('text', sa.String(length=2056), nullable=True),
    sa.Column('image', sa.String(length=35), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('NEWS', 'PUBLICATION', 'OTHER', name='posttype'), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
