"""empty message

Revision ID: b6c502e7906d
Revises: 7a242758751f
Create Date: 2023-12-19 10:32:22.406002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c502e7906d'
down_revision = '7a242758751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_caller', sa.String(length=12), nullable=False),
    sa.Column('second_caller', sa.String(length=12), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_call')
    # ### end Alembic commands ###
